/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import config.Session;
import config.dbConnector;
import config.panelPrinter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class adminPrintPreview extends javax.swing.JFrame {
    private String user_fname;
    private JPanel reportPanel;
    private String vio_id;
    
    /**
     * Creates new form adminPrintPreview
     */
    public adminPrintPreview() {
        initComponents();
 
        reportPanel = bodycolorPanel;

    }
    
    
    private void logActivity(int user_id, String action) {
        String sql = "INSERT INTO logs_table (user_id, logs_action, logs_stamp) VALUES (?, ?, NOW())";
        dbConnector db = new dbConnector();

        try (Connection conn = db.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setInt(1, user_id);
            pst.setString(2, action);
            pst.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Error logging activity: " + e.getMessage());
        }
    }
    
    

    public adminPrintPreview(String fullName, String program, String section, String address, String contact,
                         String vioNameVal, String vioDes, String vioSev, String vioStamp,
                         String recSanction, String recComment, String recStamp) {

        initComponents();

        // Student Info
        studFullName.setText(fullName);
        studProgramSection.setText(program + " - " + section);
        studAddress.setText(address);
        studCNumber.setText(contact);

        // Violation Info
        vioName.setText(vioNameVal);
        vioDesc.setText(vioDes);
        vioSevi.setText(vioSev);
        vioDate.setText(vioStamp);

        // Record Info
        actionTaken.setText(recSanction);
        comment.setText(recComment);
        dateRecorded.setText(recStamp);


        
        if (reportPanel == null) {
            reportPanel = new JPanel(); 
        }

        JButton printButton = new JButton("Print");
        printButton.setBounds(50, 500, 100, 30);
        printButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                printReport();
            }
        });

        this.add(printButton); 

    }

    private void printReport() {
        panelPrinter printer = new panelPrinter(bodycolorPanel);
       
        printer.printPanel();
        
        Session session = Session.getInstance();
    int userId = session.getUid();

    if (userId != -1) {
        logActivity(userId, "Printed a report from the admin panel.");
    } else {
        System.err.println("Session user ID not set. Cannot log print activity.");
    }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bodycolorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scc_icon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        studFullName = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        scc_icon1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        studProgramSection = new javax.swing.JLabel();
        studAddress = new javax.swing.JLabel();
        studCNumber = new javax.swing.JLabel();
        vioDate = new javax.swing.JLabel();
        vioName = new javax.swing.JLabel();
        vioSevi = new javax.swing.JLabel();
        vioDesc = new javax.swing.JLabel();
        actionTaken = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        dateRecorded = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        printButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 830));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodycolorPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodycolorPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        bodycolorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bodycolorPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, 101));

        scc_icon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        scc_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scc_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/st-cecilia-carlo-dolci-modified.png"))); // NOI18N
        bodycolorPanel.add(scc_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 100, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LASSO Supervised School");
        bodycolorPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 41, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Poblacion Ward II, Minglanilla 6046, Cebu");
        bodycolorPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("_____________________________________________________________________");
        bodycolorPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 140, 485, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("S T U D E N T    V I O L A T I O N    S Y S T E M");
        bodycolorPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 485, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("sccreq@gmail.com");
        bodycolorPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 260, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SANCTION DETAILS");
        bodycolorPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 130, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Student's Name:");
        bodycolorPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Student's Address:");
        bodycolorPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Student's Contact #:");
        bodycolorPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Recorded by:");
        bodycolorPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, 110, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Student's Program:");
        bodycolorPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));

        studFullName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studFullName.setText("studFullName");
        bodycolorPanel.add(studFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 20));

        adminName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminName.setText("Admin Name");
        bodycolorPanel.add(adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("St. Cecilia's College - Cebu, Inc.");
        bodycolorPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 20, 260, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("(032) 326 3677 / (032) 497 0767");
        bodycolorPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 78, 260, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("www.stcecilia.edu.ph");
        bodycolorPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 20));

        scc_icon1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        scc_icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scc_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scc (1).png"))); // NOI18N
        bodycolorPanel.add(scc_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 100));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("STUDENT DETAILS");
        bodycolorPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Violation Name:");
        bodycolorPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Violation Description:");
        bodycolorPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 140, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Violation Severity:");
        bodycolorPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 120, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("VIOLATION DETAILS");
        bodycolorPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 140, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Violation Date:");
        bodycolorPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Action Taken:");
        bodycolorPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 100, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Comment:");
        bodycolorPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 80, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Date Recorded:");
        bodycolorPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 110, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Reported by:");
        bodycolorPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 110, 20));

        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("User Name");
        bodycolorPanel.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 190, 40));

        studProgramSection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studProgramSection.setText("studProgramSection");
        bodycolorPanel.add(studProgramSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, 20));

        studAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studAddress.setText("studAddress");
        bodycolorPanel.add(studAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 150, 20));

        studCNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studCNumber.setText("studCNumber");
        bodycolorPanel.add(studCNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, 20));

        vioDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vioDate.setText("vioDate");
        bodycolorPanel.add(vioDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, 20));

        vioName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vioName.setText("vioName");
        bodycolorPanel.add(vioName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 150, 20));

        vioSevi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vioSevi.setText("vioSevi");
        bodycolorPanel.add(vioSevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, 20));

        vioDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vioDesc.setText("vioDesc");
        bodycolorPanel.add(vioDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 150, 20));

        actionTaken.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actionTaken.setText("actionTaken");
        bodycolorPanel.add(actionTaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 150, 20));

        comment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        comment.setText("comment");
        bodycolorPanel.add(comment, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 150, 20));

        dateRecorded.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateRecorded.setText("dateRecorded");
        bodycolorPanel.add(dateRecorded, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 150, 20));

        jPanel2.add(bodycolorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 570, 710));

        printButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel2.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 740, 130, 40));

        printButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton4.setText("Go Back");
        printButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(printButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 740, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        printReport();
    }//GEN-LAST:event_printButtonActionPerformed

    private void printButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton4ActionPerformed
        new adminRecord(user_fname, vio_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_printButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPrintPreview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionTaken;
    private javax.swing.JLabel adminName;
    private javax.swing.JPanel bodycolorPanel;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel dateRecorded;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton printButton;
    private javax.swing.JButton printButton4;
    private javax.swing.JLabel scc_icon;
    private javax.swing.JLabel scc_icon1;
    private javax.swing.JLabel studAddress;
    private javax.swing.JLabel studCNumber;
    private javax.swing.JLabel studFullName;
    private javax.swing.JLabel studProgramSection;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel vioDate;
    private javax.swing.JLabel vioDesc;
    private javax.swing.JLabel vioName;
    private javax.swing.JLabel vioSevi;
    // End of variables declaration//GEN-END:variables
}
