/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class registrationform extends javax.swing.JFrame {

    /**
     * Creates new form registrationform
     */
    public registrationform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        violationicon = new javax.swing.JLabel();
        systemlabel = new javax.swing.JLabel();
        studentlabel = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        backbutton = new javax.swing.JLabel();
        ue_textfield = new javax.swing.JTextField();
        school_id = new javax.swing.JLabel();
        user_email = new javax.swing.JLabel();
        registerlabel = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        pass_textfield = new javax.swing.JPasswordField();
        sid_textfield = new javax.swing.JTextField();
        contact_n = new javax.swing.JLabel();
        cn_textfield = new javax.swing.JTextField();
        c_password = new javax.swing.JLabel();
        cp_textfield = new javax.swing.JPasswordField();
        registerbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ifoto-ai_1738932128599.png"))); // NOI18N
        HeaderPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 130));

        getContentPane().add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 130));

        LeftPanel.setBackground(new java.awt.Color(0, 0, 0));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        violationicon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        violationicon.setForeground(new java.awt.Color(255, 255, 255));
        violationicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        violationicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/violation-logo-860-16424 (1).png"))); // NOI18N
        LeftPanel.add(violationicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 225, 90));

        systemlabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 28)); // NOI18N
        systemlabel.setForeground(new java.awt.Color(255, 255, 255));
        systemlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemlabel.setText("System");
        LeftPanel.add(systemlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 30));

        studentlabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        studentlabel.setForeground(new java.awt.Color(255, 255, 255));
        studentlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentlabel.setText("Student");
        LeftPanel.add(studentlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 220));

        RightPanel.setBackground(new java.awt.Color(204, 0, 0));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
        backbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbutton.setText("Back");
        backbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbuttonMouseExited(evt);
            }
        });
        RightPanel.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 30));

        ue_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ue_textfieldActionPerformed(evt);
            }
        });
        RightPanel.add(ue_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, -1));

        school_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        school_id.setForeground(new java.awt.Color(255, 255, 255));
        school_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        school_id.setText("School ID");
        RightPanel.add(school_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 30));

        user_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_email.setForeground(new java.awt.Color(255, 255, 255));
        user_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_email.setText("Username/Email");
        RightPanel.add(user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 30));

        registerlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerlabel.setForeground(new java.awt.Color(255, 255, 255));
        registerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerlabel.setText("REGISTER");
        RightPanel.add(registerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 30));

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setText("Password");
        RightPanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 30));

        pass_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_textfieldActionPerformed(evt);
            }
        });
        RightPanel.add(pass_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, -1));

        sid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sid_textfieldActionPerformed(evt);
            }
        });
        RightPanel.add(sid_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 220, -1));

        contact_n.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact_n.setForeground(new java.awt.Color(255, 255, 255));
        contact_n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact_n.setText("Contact Number");
        RightPanel.add(contact_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 30));

        cn_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cn_textfieldActionPerformed(evt);
            }
        });
        RightPanel.add(cn_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, -1));

        c_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c_password.setForeground(new java.awt.Color(255, 255, 255));
        c_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c_password.setText("Confirm Password");
        RightPanel.add(c_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 30));

        cp_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_textfieldActionPerformed(evt);
            }
        });
        RightPanel.add(cp_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, -1));

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(255, 255, 255));
        registerbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerbutton.setText("Register");
        registerbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerbuttonMouseExited(evt);
            }
        });
        RightPanel.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 90, 30));

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ue_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ue_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ue_textfieldActionPerformed

    private void pass_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_textfieldActionPerformed

    private void sid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sid_textfieldActionPerformed

    private void cn_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cn_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cn_textfieldActionPerformed

    private void cp_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_textfieldActionPerformed

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        new loginform().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void backbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseEntered
        backbutton.setForeground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_backbuttonMouseEntered

    private void backbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseExited
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_backbuttonMouseExited

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbuttonMouseClicked

    private void registerbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseEntered
        registerbutton.setForeground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_registerbuttonMouseEntered

    private void registerbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseExited
        registerbutton.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_registerbuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel backbutton;
    private javax.swing.JLabel c_password;
    private javax.swing.JTextField cn_textfield;
    private javax.swing.JLabel contact_n;
    private javax.swing.JPasswordField cp_textfield;
    private javax.swing.JLabel header;
    private javax.swing.JPasswordField pass_textfield;
    private javax.swing.JLabel password;
    private javax.swing.JLabel registerbutton;
    private javax.swing.JLabel registerlabel;
    private javax.swing.JLabel school_id;
    private javax.swing.JTextField sid_textfield;
    private javax.swing.JLabel studentlabel;
    private javax.swing.JLabel systemlabel;
    private javax.swing.JTextField ue_textfield;
    private javax.swing.JLabel user_email;
    private javax.swing.JLabel violationicon;
    // End of variables declaration//GEN-END:variables
}
