

import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class registrationform extends javax.swing.JFrame {

    /**
     * Creates new form registrationform
     */
    public registrationform() {
        initComponents();
    }
    
    public static String passwordHash(String user_password){
        try{
            
            MessageDigest md = MessageDigest.getInstance("SHA");
            md.update(user_password.getBytes());
            byte[] rbt = md.digest();
            StringBuilder sb = new StringBuilder();
            
            for(byte b: rbt){
                sb.append(String.format("%02x", b));
            }          
            return sb.toString();
        }catch(Exception e){
            
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        violationicon = new javax.swing.JLabel();
        systemlabel = new javax.swing.JLabel();
        studentlabel = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        backbutton = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        user_emaillabel = new javax.swing.JLabel();
        registerlabel = new javax.swing.JLabel();
        user_passwordlabel = new javax.swing.JLabel();
        user_fnamelabel = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        registerbutton = new javax.swing.JLabel();
        user_cnumberlabel = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        user_typelabel = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox<>();
        cn_error = new javax.swing.JLabel();
        pass_error = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ifoto-ai_17389321285992.png"))); // NOI18N
        HeaderPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        getContentPane().add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 150));

        LeftPanel.setBackground(new java.awt.Color(0, 0, 0));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        violationicon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        violationicon.setForeground(new java.awt.Color(255, 255, 255));
        violationicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        violationicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/violation-logo-860-16424 (1).png"))); // NOI18N
        LeftPanel.add(violationicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 225, 90));

        systemlabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 28)); // NOI18N
        systemlabel.setForeground(new java.awt.Color(255, 255, 255));
        systemlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemlabel.setText("System");
        LeftPanel.add(systemlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 30));

        studentlabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 30)); // NOI18N
        studentlabel.setForeground(new java.awt.Color(255, 255, 255));
        studentlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentlabel.setText("Student");
        LeftPanel.add(studentlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 40));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 200));

        RightPanel.setBackground(new java.awt.Color(204, 0, 0));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton.setBackground(new java.awt.Color(255, 255, 255));
        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
        backbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbutton.setText("Back");
        backbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbuttonMouseExited(evt);
            }
        });
        RightPanel.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 30));

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        RightPanel.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, -1));

        user_emaillabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_emaillabel.setForeground(new java.awt.Color(255, 255, 255));
        user_emaillabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_emaillabel.setText("Email:");
        RightPanel.add(user_emaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 20));

        registerlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerlabel.setForeground(new java.awt.Color(255, 255, 255));
        registerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerlabel.setText("REGISTER");
        RightPanel.add(registerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 40));

        user_passwordlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        user_passwordlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_passwordlabel.setText("Password:");
        RightPanel.add(user_passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 20));

        user_fnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_fnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        user_fnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_fnamelabel.setText("Full Name:");
        RightPanel.add(user_fnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        fullNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTextFieldActionPerformed(evt);
            }
        });
        RightPanel.add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, -1));

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(255, 255, 255));
        registerbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerbutton.setText("Register");
        registerbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerbuttonMouseExited(evt);
            }
        });
        RightPanel.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 80, 30));

        user_cnumberlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_cnumberlabel.setForeground(new java.awt.Color(255, 255, 255));
        user_cnumberlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_cnumberlabel.setText("Contact Number:");
        RightPanel.add(user_cnumberlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        contactNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });
        contactNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactNumberTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNumberTextFieldKeyReleased(evt);
            }
        });
        RightPanel.add(contactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, -1));

        user_typelabel.setBackground(new java.awt.Color(255, 255, 255));
        user_typelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_typelabel.setForeground(new java.awt.Color(255, 255, 255));
        user_typelabel.setText("User Type:");
        RightPanel.add(user_typelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 20));

        userTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        userTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeComboBoxActionPerformed(evt);
            }
        });
        RightPanel.add(userTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, -1));

        cn_error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cn_error.setForeground(new java.awt.Color(255, 255, 0));
        cn_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightPanel.add(cn_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, 20));

        pass_error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pass_error.setForeground(new java.awt.Color(255, 255, 0));
        pass_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_error.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass_errorKeyReleased(evt);
            }
        });
        RightPanel.add(pass_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, 20));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        RightPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 250, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void fullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextFieldActionPerformed

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        new loginform().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void backbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseEntered
        backbutton.setForeground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_backbuttonMouseEntered

    private void backbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseExited
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_backbuttonMouseExited

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
        String user_fname = fullNameTextField.getText();
        String user_cnumber = contactNumberTextField.getText();
        String user_email = emailTextField.getText();
        String user_password = passwordHash(passwordField.getText());
        String user_type = userTypeComboBox.getSelectedItem().toString();
        String user_status = "Pending";

        if (user_fname.isEmpty() || user_cnumber.isEmpty() || user_email.isEmpty() || user_password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!user_cnumber.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Contact number must be in digits.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (user_password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password should have at least 8 characters.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!user_email.toLowerCase().endsWith(".com")) {
            JOptionPane.showMessageDialog(this, "Email must be valid. Please enter a valid email account.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String url = "jdbc:mysql://localhost:3306/sumbi_db";
        String user = "root";
        String pass = "";

        try {
            Connection conn = DriverManager.getConnection(url, user, pass);

            if (isEmailDuplicate(conn, user_email)) {
                JOptionPane.showMessageDialog(this, "Email already exists. Please use a different email.", "Error", JOptionPane.ERROR_MESSAGE);
                conn.close();
                return;
            }

            String sql = "INSERT INTO user_table (user_fname, user_cnumber, user_email, user_password, user_type, user_status) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1, user_fname);
            pstmt.setString(2, user_cnumber);
            pstmt.setString(3, user_email);
            pstmt.setString(4, user_password);
            pstmt.setString(5, user_type);
            pstmt.setString(6, user_status);

            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Registration successful! Please wait for admin approval.");
                this.dispose();
                new loginform().setVisible(true);
            }

            pstmt.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_registerbuttonMouseClicked

    private boolean isEmailDuplicate(Connection conn, String email) {
        boolean exists = false;
        String query = "SELECT COUNT(*) FROM user_table WHERE user_email = ?";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, email);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                exists = rs.getInt(1) > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return exists;
    }
    
    private void registerbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseEntered
        registerbutton.setForeground(new java.awt.Color(255, 255, 0));
    }//GEN-LAST:event_registerbuttonMouseEntered

    private void registerbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseExited
        registerbutton.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_registerbuttonMouseExited

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void userTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTypeComboBoxActionPerformed

    private void contactNumberTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberTextFieldKeyReleased
        String user_cnumber = contactNumberTextField.getText();
        if(!user_cnumber.matches("\\d+")){
            cn_error.setText("must be digit!");
        }else{
            cn_error.setText(null);
        }
    }//GEN-LAST:event_contactNumberTextFieldKeyReleased

    private void contactNumberTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldKeyPressed

    private void pass_errorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_errorKeyReleased
        
    }//GEN-LAST:event_pass_errorKeyReleased

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        String user_password = passwordField.getText();
        if(user_password.length()<7){
            pass_error.setText("at least 8 characters!");
        }else{
            pass_error.setText(null);
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel backbutton;
    private javax.swing.JLabel cn_error;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel header;
    private javax.swing.JLabel pass_error;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel registerbutton;
    private javax.swing.JLabel registerlabel;
    private javax.swing.JLabel studentlabel;
    private javax.swing.JLabel systemlabel;
    private javax.swing.JComboBox<String> userTypeComboBox;
    private javax.swing.JLabel user_cnumberlabel;
    private javax.swing.JLabel user_emaillabel;
    private javax.swing.JLabel user_fnamelabel;
    private javax.swing.JLabel user_passwordlabel;
    private javax.swing.JLabel user_typelabel;
    private javax.swing.JLabel violationicon;
    // End of variables declaration//GEN-END:variables
}
